### ISSUE TITLE
error when some data in mongodb had been updated

### ISSUE THREAD

**Issue by kendozen** [mongodb-labs/solr-doc-manager#6]
when updating data，it throw en exception such as behind:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/site-packages/mongo_connector/util.py", line 107, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 298, in run
    entry["o2"]["_id"], entry["o"], ns, timestamp
  File "/usr/local/lib/python3.5/site-packages/mongo_connector/util.py", line 33, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/solr_doc_manager-0.1.0-py3.5.egg/mongo_connector/doc_managers/solr_doc_manager.py", line 252, in update
    doc.pop('ns')
KeyError: 'ns'

so when debuging the source, I found that there's no ns in doc，so after I comment it, it does work.

**Comment by mitereiter** [comment]
did you managed to resolve this problem?

**Comment by AndrewG10i** [comment]
@jekeans it seems that your `schema.xml` is mis-configured. Make sure that it follows the [provided sample](https://github.com/yougov/solr-doc-manager/blob/master/mongo_connector/doc_managers/schema.xml).

Particularly these lines should be present:
```xml
   <!-- metadata used by mongo-connector -->
   <field name="_ts" type="long" indexed="true" stored="true" required="true" multiValued="false" />
   <field name="ns" type="string" indexed="true" stored="true" required="true" multiValued="false" />
```

Hope this helps. Thanks!
