### ISSUE TITLE
importlib_metadata.api.PackageNotFoundError

### ISSUE THREAD

**Issue by Leehory** [mongodb-labs/solr-doc-manager#7]
Traceback (most recent call last):
  File "/usr/local/bin/mongo-connector", line 11, in <module>
    load_entry_point('mongo-connector==3.1.1', 'console_scripts', 'mongo-connector')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/mongo_connector-3.1.1-py3.7.egg/mongo_connector/connector.py", line
    from mongo_connector import config, constants, errors, util
  File "/usr/local/lib/python3.7/site-packages/mongo_connector-3.1.1-py3.7.egg/mongo_connector/config.py", line 20
    from mongo_connector.constants import __version__
  File "/usr/local/lib/python3.7/site-packages/mongo_connector-3.1.1-py3.7.egg/mongo_connector/constants.py", line
    import importlib_metadata
  File "/usr/local/lib/python3.7/site-packages/importlib_metadata-0.11-py3.7.egg/importlib_metadata/__init__.py", 
    __version__ = version(__name__)
  File "/usr/local/lib/python3.7/site-packages/importlib_metadata-0.11-py3.7.egg/importlib_metadata/api.py", line 
    return distribution(package).version
  File "/usr/local/lib/python3.7/site-packages/importlib_metadata-0.11-py3.7.egg/importlib_metadata/api.py", line 
    return Distribution.from_name(package)
  File "/usr/local/lib/python3.7/site-packages/importlib_metadata-0.11-py3.7.egg/importlib_metadata/api.py", line 
    raise PackageNotFoundError(name)
importlib_metadata.api.PackageNotFoundError: importlib_metadata

help-----thanks

**Comment by Leehory** [comment]
importlib_metadata0.12自行解决了
